json.id user.id
json.name user.name
json.email user.email
json.phone_number user.phone_number
json.birth_date user.birth_date
json.weight_in_pounds user.weight
json.target_weight user.target_weight
json.target_waist_size user.target_waist_size
json.waist_size user.waist_size
json.height_in_inches user.height
json.routines user.routines